---
instances:
  - name: app1
    keypair: 2ea5-keypair
    image: rhel-8.3
    flavor: GLOBAL-CPU_4_Memory_8192_Disk_30_flavor
    security_group: 2ea5-HostSG
    internal_network: 2ea5-dev-network
    metadata:
      AnsibleGroup: osp_instances
      deployment_name: finallab

  - name: app2
    keypair: 2ea5-keypair
    image: rhel-8.3
    flavor: GLOBAL-CPU_4_Memory_8192_Disk_30_flavor
    security_group: 2ea5-HostSG
    internal_network: 2ea5-dev-network
    metadata:
      AnsibleGroup: osp_instances
      deployment_name: finallab

  - name: appdb1
    keypair: 2ea5-keypair
    image: rhel-8.3
    flavor: GLOBAL-CPU_4_Memory_8192_Disk_30_flavor
    security_group: 2ea5-HostSG
    internal_network: 2ea5-dev-network
    metadata:
      AnsibleGroup: osp_instances
      deployment_name: finallab

  - name: frontend1
    keypair: 2ea5-keypair
    image: rhel-8.3
    flavor: GLOBAL-CPU_4_Memory_8192_Disk_30_flavor
    security_group: 2ea5-HostSG
    internal_network: 2ea5-dev-network
    metadata:
      AnsibleGroup: osp_instances
      deployment_name: finallab
